server:
   max-http-header-size: 10000
   port: 8502
   
jdb:
  orm:
    filepath: jdb-orm.conf.xml
    data-source-close-method-name: close
    
spring:
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:sqlserver://localhost:1433;DatabaseName=SMT_ALL
        username: sa
        password: root
  application: 
      name: smt-base

smt:
  parent:
    code:
      filter:
        cors:
          access-control-allow-methods: GET,POST,PUT,DELETE
          access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, _log, token
          access-control-max-age: 1800
        token:
          ignore-url-patterns:
          - /account/login
          - /account/token/validate/*

# 指定该服务要注册进指定url的服务注册中心  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.252:8501/eureka/
