USE [SMT_BASE]




GO
-- 初始化用户账号信息
DECLARE @USER_ID VARCHAR(36)
DECLARE @ACCOUNT_ID VARCHAR(36)

--GUEST_001
SET @USER_ID = NEWID()
SET @ACCOUNT_ID = NEWID()
INSERT INTO [dbo].[SMT_USER]([ID] ,[ACCOUNT_ID] ,[TYPE] ,[NIKE_NAME] ,[REAL_NAME] ,[SEX] ,[PHONE_NUM] ,[EMAIL],[CREATE_USER_ID] ,[CREATE_DATE])
VALUES (@USER_ID ,@ACCOUNT_ID ,0 ,'GUEST_001' ,'GUEST_001' ,1 ,NULL ,'grandia-4727@163.com' ,'super_admin' , GETDATE())

INSERT INTO [dbo].[SMT_ACCOUNT]([ID],[LOGIN_NAME],[LOGIN_PWD],[LOGIN_KEY],[STATE],[EXPIRY_DATE] ,[REMARK] ,[USER_ID] ,[OPEN_USER_ID] ,[OPEN_DATE])
VALUES (@ACCOUNT_ID,'guest_001','guest','guest' ,1 ,DATEADD(day,1000,GETDATE()) ,'系统内置测试账号_001',@USER_ID,'super_admin' , GETDATE())

--GUEST_002
SET @USER_ID = NEWID()
SET @ACCOUNT_ID = NEWID()
INSERT INTO [dbo].[SMT_USER]([ID] ,[ACCOUNT_ID] ,[TYPE] ,[NIKE_NAME] ,[REAL_NAME] ,[SEX] ,[PHONE_NUM] ,[EMAIL],[CREATE_USER_ID] ,[CREATE_DATE])
VALUES (@USER_ID ,@ACCOUNT_ID ,0 ,'GUEST_002' ,'GUEST_002' ,1 ,NULL ,'grandia-4727@163.com' ,'super_admin' , GETDATE())

INSERT INTO [dbo].[SMT_ACCOUNT]([ID],[LOGIN_NAME],[LOGIN_PWD],[LOGIN_KEY],[STATE],[EXPIRY_DATE] ,[REMARK] ,[USER_ID] ,[OPEN_USER_ID] ,[OPEN_DATE])
VALUES (@ACCOUNT_ID,'guest_002','guest','guest' ,1 ,DATEADD(day,1000,GETDATE()) ,'系统内置测试账号_002',@USER_ID,'super_admin' , GETDATE())

--GUEST_003
SET @USER_ID = NEWID()
SET @ACCOUNT_ID = NEWID()

INSERT INTO [dbo].[SMT_USER]([ID] ,[ACCOUNT_ID] ,[TYPE] ,[NIKE_NAME] ,[REAL_NAME] ,[SEX] ,[PHONE_NUM] ,[EMAIL],[CREATE_USER_ID] ,[CREATE_DATE])
VALUES (@USER_ID ,@ACCOUNT_ID ,0 ,'GUEST_003' ,'GUEST_003' ,1 ,NULL ,'grandia-4727@163.com' ,'super_admin' , GETDATE())

INSERT INTO [dbo].[SMT_ACCOUNT]([ID],[LOGIN_NAME],[LOGIN_PWD],[LOGIN_KEY],[STATE],[EXPIRY_DATE] ,[REMARK] ,[USER_ID] ,[OPEN_USER_ID] ,[OPEN_DATE])
VALUES (@ACCOUNT_ID,'guest_003','guest','guest' ,1 ,DATEADD(day,1000,GETDATE()) ,'系统内置测试账号_003',@USER_ID,'super_admin' , GETDATE())

-- Administrator
SET @USER_ID = NEWID()
SET @ACCOUNT_ID = NEWID()
INSERT INTO [dbo].[SMT_USER]([ID] ,[ACCOUNT_ID] ,[TYPE] ,[NIKE_NAME] ,[REAL_NAME] ,[SEX] ,[PHONE_NUM] ,[EMAIL],[CREATE_USER_ID]  ,[CREATE_DATE])
VALUES (@USER_ID ,@ACCOUNT_ID ,0 ,'Administrator' ,'Administrator' ,1 ,NULL ,'grandia-4727@163.com' ,'super_admin' , GETDATE())

INSERT INTO [dbo].[SMT_ACCOUNT]([ID],[LOGIN_NAME],[LOGIN_PWD],[LOGIN_KEY],[STATE],[EXPIRY_DATE] ,[REMARK] ,[USER_ID] ,[OPEN_USER_ID] ,[OPEN_DATE])
VALUES (@ACCOUNT_ID,'Administrator','admin','Administrator' ,1 ,DATEADD(day,1000,GETDATE()) ,'系统内置管理账号',@USER_ID,'super_admin' ,GETDATE())
GO

SELECT * FROM SMT_ACCOUNT

SELECT * FROM SMT_USER

GO
-- 初始化项目信息
DECLARE @PROJECT_CODE VARCHAR(50)
DECLARE @IDENTITY_ID INT

SET @PROJECT_CODE = 'COMPANY_PROJECT'

INSERT INTO [dbo].[SMT_PROJECT]([PARENT_ID],[CODE],[LEVEL_],[NAME],[DESCRIPTION],[TYPE],[STATE],[CREATE_USER_ID],[CREATE_DATE] ,[TENANT_ID] ,[BUFFER_ID] ,[AUTH_CODE])
VALUES (NULL,@PROJECT_CODE,@PROJECT_CODE,'制造信息化管控项目','制造信息化管控项目（说明）',1,1 ,'D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA',GETDATE() ,'SMT' ,'' ,'SMT_AUTH_001')

SET @IDENTITY_ID = @@IDENTITY

SET @PROJECT_CODE = 'PROJECT_APP'

INSERT INTO [dbo].[SMT_PROJECT]([PARENT_ID],[CODE],[LEVEL_],[NAME],[DESCRIPTION],[TYPE],[STATE],[CREATE_USER_ID],[CREATE_DATE] ,[TENANT_ID] ,[BUFFER_ID] ,[AUTH_CODE])
VALUES (@IDENTITY_ID ,@PROJECT_CODE,@PROJECT_CODE ,'制造信息化管控系统' ,'制造信息化管控系统（说明）' ,1 ,1 ,'D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA' ,GETDATE() ,'SMT','' ,'SMT_AUTH_001')

SET @PROJECT_CODE = 'PROJECT_MOBILE'

INSERT INTO [dbo].[SMT_PROJECT]([PARENT_ID],[CODE],[LEVEL_],[NAME],[DESCRIPTION],[TYPE],[STATE],[CREATE_USER_ID],[CREATE_DATE] ,[TENANT_ID] ,[BUFFER_ID] ,[AUTH_CODE])
VALUES (@IDENTITY_ID,@PROJECT_CODE ,@PROJECT_CODE,'制造信息化管控触摸端系统' ,'制造信息化管控触摸端系统（说明）' ,1 ,1 ,'D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA' ,GETDATE() ,'SMT','' ,'SMT_AUTH_001')

SELECT * FROM SMT_PROJECT
GO

GO
-- 初始化组织机构信息
DECLARE @DEPT_CODE VARCHAR(50)
DECLARE @DEPT_IDENTITY INT
SET @DEPT_CODE = 'COMPANY_MAIN'
INSERT INTO [dbo].[SMT_ORG]([PARENT_ID],[TYPE],[CODE],[NAME] ,[DESCRIPTION],[PROJECT_CODE],[TENANT_ID])
VALUES (NULL,1,@DEPT_CODE,'集团公司','集团公司(上市集团)','COMPANY_PROJECT' ,'SMT')

SET @DEPT_IDENTITY = @@IDENTITY

SET @DEPT_CODE = 'DEPT_FINACE'
INSERT INTO [dbo].[SMT_ORG]([PARENT_ID],[TYPE],[CODE],[NAME] ,[DESCRIPTION],[PROJECT_CODE],[TENANT_ID])
VALUES (@DEPT_IDENTITY,2,@DEPT_CODE,'财务部','集团总公司(上市集团)','COMPANY_PROJECT' ,'SMT')

SET @DEPT_CODE = 'DEPT_MARKET'
INSERT INTO [dbo].[SMT_ORG]([PARENT_ID],[TYPE],[CODE],[NAME] ,[DESCRIPTION],[PROJECT_CODE],[TENANT_ID])
VALUES (@DEPT_IDENTITY,2,@DEPT_CODE,'市场部','集团总公司(上市集团)','COMPANY_PROJECT' ,'SMT')

SET @DEPT_CODE = 'DEPT_RESEARCH'
INSERT INTO [dbo].[SMT_ORG]([PARENT_ID],[TYPE],[CODE],[NAME] ,[DESCRIPTION],[PROJECT_CODE],[TENANT_ID])
VALUES (@DEPT_IDENTITY,2,@DEPT_CODE,'研发部','集团总公司(上市集团)','COMPANY_PROJECT' ,'SMT')

SET @DEPT_CODE = 'DEPT_SELL'
INSERT INTO [dbo].[SMT_ORG]([PARENT_ID],[TYPE],[CODE],[NAME] ,[DESCRIPTION],[PROJECT_CODE],[TENANT_ID])
VALUES (@DEPT_IDENTITY,2,@DEPT_CODE,'销售部','集团总公司(上市集团)','COMPANY_PROJECT' ,'SMT')

SELECT * FROM SMT_ORG
GO

select * from SMT_USER
select * from SMT_ORG

-- 组织结构人员关系表
INSERT INTO [dbo].[SMT_USER_ORG_LINK]([USER_ID],[ORG_CODE],[TENANT_ID])
VALUES('D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA','COMPANY_MAIN','SMT')

INSERT INTO [dbo].[SMT_USER_ORG_LINK]([USER_ID],[ORG_CODE],[TENANT_ID])
VALUES('3563CE02-F747-47CE-AE8E-95F41B53E514','DEPT_FINACE','SMT')

INSERT INTO [dbo].[SMT_USER_ORG_LINK]([USER_ID],[ORG_CODE],[TENANT_ID])
VALUES('0E385A20-A86F-44FF-8E69-45AF0832BA9C','DEPT_MARKET','SMT')

INSERT INTO [dbo].[SMT_USER_ORG_LINK]([USER_ID],[ORG_CODE],[TENANT_ID])
VALUES('5D765407-2AEA-484D-B947-058A8C232C49','DEPT_SELL','SMT')
GO



--初始化角色信息

INSERT INTO [dbo].[SMT_ROLE]([CODE],[NAME],[DESCRIPTION] ,[STATE],[CREATE_USER_ID],[CREATE_DATE],[PROJECT_CODE],[TENANT_ID])
VALUES('ROLE_ADMIN' ,'Admin','管理员' ,1,'D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA',GETDATE(),'COMPANY_PROJECT' ,'SMT')

INSERT INTO [dbo].[SMT_ROLE]([CODE],[NAME],[DESCRIPTION] ,[STATE],[CREATE_USER_ID],[CREATE_DATE],[PROJECT_CODE],[TENANT_ID])
VALUES('ROLE_MANAGER' ,'经理','经理' ,1,'D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA',GETDATE(),'COMPANY_PROJECT' ,'SMT')

INSERT INTO [dbo].[SMT_ROLE]([CODE],[NAME],[DESCRIPTION] ,[STATE],[CREATE_USER_ID],[CREATE_DATE],[PROJECT_CODE],[TENANT_ID])
VALUES('ROLE_LEADER' ,'主管','主管' ,1,'D3B030D5-1F8E-48DA-A740-7B8EECFAEFEA',GETDATE(),'COMPANY_PROJECT' ,'SMT')

SELECT * FROM SMT_ROLE
GO

